config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'companies/index'

  resources :customers, :companies

  root 'companies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/companie.rb
class Companie < ApplicationRecord

  belongs_to :person

   has_many :events
   has_many :customers, through: :events
end

app/models/customer.rb
class Customer < ApplicationRecord

  belongs_to :person

   has_many :events
   has_many :companies, through: :events

end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :customer
  belongs_to :companie

end

app/models/person.rb
class Person < ApplicationRecord

  has_one :customer
  has_one :companie

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index

    @companies = Companie.all

  end

  def new

  end

  def create

    @person = Person.new
    @person.name = param_companie[:name]

    @companie = Companie.new
    @companie.person = @person
    @companie.cnpj = param_companie[:cnpj]
    @companie.nickname = param_companie[:nickname]
    @companie.save
    redirect_to @companie

  end


  def show

    @companie = Companie.find(params[:id])

  end

   def edit

    @companie = Companie.find(params[:id])

  end

  def update

    @companie = Companie.find(params[:id])
    flash[:notice] = "#was successfully updated."
    redirect_to company_path(@companie)
  end

  def destroy

    @companie = Companie.find(params[:id])
    @companie.destroy

    redirect_to companies_path

  end

  private

  def param_companie

   (params.require(:companie).permit(:name, :cnpj, :nickname))

  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index

    @customers = Customer.all

  end

  def new

  end

  def create

    puts param_customer
    @person = Person.new
    @person.name = param_customer[:name]

    @customer = Customer.new
    @customer.person = @person
    @customer.cpf = param_customer[:cpf]
    @customer.nickname = param_customer[:nickname]
    @customer.save
    redirect_to @customer

  end

  def show

    @customer = Customer.find(params[:id])


  end

  def edit

    @customer = Customer.find(params[:id])


  end

  def update
    @customer = Customer.find(params[:id])
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to customer_path(@customer)
  end

  def destroy

    @customer = Customer.find(params[:id])
    @customer.destroy

    redirect_to customers_path

  end

  private

  def param_customer

    (params.require(:customer).permit(:name, :cpf, :nickname))

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/edit.html.erb
<%= form_with(model: @companie,  method: "put") do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :person_id %>
  </p>

  <p>
    <%= form.label :cnpj %><br>
    <%= form.text_field :cnpj %>
  </p>

  <p>
    <%= form.label :nickname %><br>
    <%= form.text_area :nickname %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/companies/index.html.erb
<h1>Listando Empresas</h1>

<table>
  <tr>
    <th>Empresa</th>
    <th>Cnpj</th>
    <th>Apelido</th>


    <th></th>

  </tr>

  <% @companies.each do |c| %>
    <tr>
      <td><%= c.person.name %></td><br/>
      <td><%= c.cnpj %></td>
      <td><%= c.nickname %></td>

      <td><%= link_to 'Mostrar Empresa', company_path(c) %></td>
      <td><%= link_to 'Editar Empresa', edit_company_path(c) %></td>
      <td><%= link_to 'Excluir Cliente', company_path(c), method: :delete, data: {confirm: 'Tem certeza que deseja deletar?'} %></td>

    </tr>


     <% end %>
</table>

<br>

     <td><%= link_to 'Criar Empresa', new_company_path %></td>

app/views/companies/new.html.erb
<%= form_with scope: :companie, local: true, url: companies_path do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :nickname %><br>
    <%= form.text_area :nickname %>
  </p>

  <p>
    <%= form.label :cnpj %><br>
    <%= form.text_area :cnpj %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/companies/show.html.erb
<p>
  <br>
  <strong>Empresa:</strong>
  <%= @companie.person.name %>
</p>

<p>
  <br>
  <strong>Cnpj:</strong>
  <%= @companie.cnpj %>
</p>


<br>


<%= link_to 'Voltar', companies_path %>

app/views/customers/edit.html.erb
<%= form_with(model: @customer, local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :person_id %>
  </p>

  <p>
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf %>
  </p>

  <p>
    <%= form.label :nickname %><br>
    <%= form.text_area :nickname %>
  </p>

  <p>
    <%= form.submit %>
  </p>

  <%= link_to 'Voltar', customers_path %>

<% end %>

app/views/customers/index.html.erb
<h1>Listando Clientes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Cpf</th>
    <th>Apelido</th>

    <th></th>
  </tr>

  <% @customers.each do |c| %>
    <tr>
      <td><%= c.person.name %></td><br/>
      <td><%= c.cpf %></td>
      <td><%= c.nickname %></td>

      <td><%= link_to 'Mostrar Cliente', customer_path(c) %></td>
      <td><%= link_to 'Editar Cliente', edit_customer_path(c) %></td>
      <td><%= link_to 'Excluir Cliente', customer_path(c), method: :delete, data: {confirm: 'Tem certeza que deseja deletar?'} %></td>


    </tr>




     <% end %>
</table>

<td><%= link_to 'Criar Cliente', new_customer_path%></td>

app/views/customers/new.html.erb
<%= form_with scope: :customer, local: true, url: customers_path do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :nickname %><br>
    <%= form.text_area :nickname %>
  </p>

  <p>
    <%= form.label :cpf %><br>
    <%= form.text_area :cpf %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/customers/show.html.erb
<p>
  <br>
  <strong>Cliente:</strong>
  <%= @customer.person.name %>
</p>

<p>
  <br>
  <strong>CPF:</strong>
  <%= @customer.cpf %>
</p>


<br>


<%= link_to 'Voltar', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Controle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>